repos:
- repo: local
  hooks:
    - id: prettier
      name: prettier
      entry: bash -c "npx prettier --write ./frontend/src"
      language: system
- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.11.10
  hooks:
    # Linter
    - id: ruff
      files: ./backend
      args: [ --fix ]
    # Formatter
    - id: ruff-format
      files: ./backend
