services:

  backend:
    build: ./backend
    container_name: backend-dev
    volumes:
      - ./data/db:/backend/data/db
      - ./data/env:/env
      - ./data/logs:/backend/data/logs
      - ./data/storage:/backend/data/storage
    environment:
      - PATH_TO_DB=/backend/data/db/db.sqlite3
      - PATH_TO_ENV=/env
      - PATH_TO_STORAGE=/backend/data/storage
      - RSA_PRIVATE_KEY=private_key.pem
      - RSA_PUBLIC_KEY=public_key.pem
      - SSL_CERT=certfile.crt
      - SSL_KEY=keyfile.key
      - PATH_TO_LOGS=/backend/data/logs
      - BACKEND_LOG=backend.log
    env_file:
      - .env
    networks:
      network:
        ipv4_address: 172.16.1.2

  frontend:
    build: ./frontend
    container_name: frontend-dev
    volumes:
      - ./data/env:/env
      - ./data/storage:/usr/share/nginx/html/storage
    env_file:
      - .env
    networks:
      network:
        ipv4_address: 172.16.1.3
    depends_on:
      - backend

volumes:
  db:
  env:
  storage:

networks:
  network:
    ipam:
      config:
        - subnet: 172.16.1.0/24
