services:

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: lts-backend
    restart: unless-stopped
    volumes:
      - /etc/localtime:/etc/localtime
      - ./data/db:/backend/data/db
      - ./data/env:/env
      - ./data/logs:/backend/data/logs
      - ./data/storage:/backend/data/storage
    environment:
      - PATH_TO_DB=/backend/data/db/db.sqlite3
      - PATH_TO_ENV=/env
      - PATH_TO_STORAGE=/backend/data/storage
      - RSA_PRIVATE_KEY=RSA_private_key.pem
      - RSA_PUBLIC_KEY=RSA_public_key.pem
      - PATH_TO_LOGS=/backend/data/logs
      - BACKEND_LOG=backend.log
    env_file:
      - .env
    networks:
      - lts_network
    ports:
      - "37190:37190"
    develop:
      watch:
        - action: rebuild
          path: ./backend

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: lts-frontend
    restart: unless-stopped
    volumes:
      - /etc/localtime:/etc/localtime
      - ./data/env:/env
      - ./data/storage:/usr/share/nginx/html/storage/storage
    env_file:
      - .env
    networks:
      - lts_network
    ports:
      - "${FRONTEND_PORT:-31022}:${FRONTEND_PORT:-31022}"
    depends_on:
      - backend
    develop:
      watch:
        - action: rebuild
          path: ./frontend

networks:
  lts_network:
    driver: bridge
