services:

  postgres:
    image: postgres:latest
    container_name: lts-postgres
    restart: unless-stopped
    env_file:
      - .env
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "${POSTGRES_PORT:-54321}:5432"
    volumes:
      - ./data/pg:/var/lib/postgresql/data/pgdata
      - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - lts_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: lts-backend
    restart: unless-stopped
    volumes:
      - /etc/localtime:/etc/localtime
      - ./data/db:/backend/data/db
      - ./data/env:/env
      - ./data/logs:/backend/data/logs
      - ./data/storage:/backend/data/storage
    environment:
      - PATH_TO_DB=/backend/data/db/db.sqlite3
      - PATH_TO_ENV=/env
      - PATH_TO_STORAGE=/backend/data/storage
      - RSA_PRIVATE_KEY=RSA_private_key.pem
      - RSA_PUBLIC_KEY=RSA_public_key.pem
      - PATH_TO_LOGS=/backend/data/logs
      - BACKEND_LOG=backend.log
      - POSTGRES_HOST=postgres
    env_file:
      - .env
    networks:
      - lts_network
    ports:
      - "37190:37190"
    depends_on:
      postgres:
        condition: service_healthy
    develop:
      watch:
        - action: rebuild
          path: ./backend

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: lts-frontend
    restart: unless-stopped
    volumes:
      - /etc/localtime:/etc/localtime
      - ./data/env:/env
      - ./data/storage:/usr/share/nginx/html/storage/storage
    env_file:
      - .env
    networks:
      - lts_network
    ports:
      - "${FRONTEND_PORT:-31022}:${FRONTEND_PORT:-31022}"
    depends_on:
      - backend
    develop:
      watch:
        - action: rebuild
          path: ./frontend

networks:
  lts_network:
    driver: bridge
