name: Auto merge the dev branch into main at night
on:
  schedule:
    - cron: "0 1 * * *"  # 01:00 (24-hour format)
jobs:
  merge-dev-into-main:
    runs-on: ubuntu-latest
    environment: auto-merge-dev-branch-into-main-at-night-actions-env
    steps:
      - uses: actions/checkout@v4
      - name: Fetch branches
        run: git fetch
      - name: Checkout the dev branch
        run: git checkout dev
      - name: Checkout the main branch
        run: git checkout main
      - name: Merge the dev branch into main
        run: git merge dev
      - name: Push the main branch
        run: git push origin main
